version: '3.3'

services:
  cbs:
    image: 'yd1722/tuum_cbs:latest'
    build:
      context: .
    container_name: tuum_cbs
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cbs_mq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tuum_cbs
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_RABBITMQ_HOST=cbs_mq
      - SPRING_RABBITMQ_PORT=15672

  db:
    image: 'postgres'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tuum_cbs
    volumes:
      - ./postgres/db_dump/tuum_cbs.sql:/docker-entrypoint-initdb.d/tuum_cbs.sql

  cbs_mq:
    image: rabbitmq:3-management-alpine
    container_name: cbs_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
