version: '3.3'

services:
  cbs:
    image: 'tuum_cbs:latest'
    build:
      context: .
    container_name: tuum_cbs
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tuum_cbs
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123

  db:
    image: 'tuum_cbs_db:latest'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  rabbit:
    container_name: tuum_cbs_mq
    image: rabbitmq:3-management-alpine
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"